# This is a basic workflow to help you get started with Actions

name: Publish Group Webiste

# Setup the workflow to run whenever there is a push (e.g., throug a PR merge)
# to the primary branch, whatever naming convention is being used.
on:
  push:
    branches:
      - master
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # The type of runner that the job will run on
      - name: Ensure validation
        uses: connorjbracy/rg-db-public@main
        secrets:
          token: ${{ secrets.GH_ACTIONS_PAT }}

      - name: Deploy Group Website
        uses: connorjbracy/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_ACTIONS_PAT }}
        with:
          source_file: 'website/_build/html/*'
          destination_repo: 'Billingegroup/billingegroup.github.io'
          destination_branch: 'master'
          user_email: 'simon.billinge@gmail.com'
          user_name: 'sbillinge'
